main.js

import bootstrap.js

---

pages/index.html

Revert "更新了一行"

---

assets/scss/_variables.scss
assets/scss/all.scss
main.js
pages/index.html

add: feat/component

---

assets/scss/_utilities.scss
assets/scss/all.scss

添加 BS 的文字斷點

---

assets/scss/pages/_course_introduction.scss
pages/course_introduction.html

新增modal、教師行事曆版型修正

---

assets/scss/_utilities.scss
assets/scss/all.scss
assets/scss/components/_btn.scss
assets/scss/components/_datepicker.scss
assets/scss/pages/_cart.scss
assets/scss/utils/_helpers.scss
main.js
package-lock.json
package.json
pages/account.html
pages/cart.html
pages/cart2.html
pages/cart3.html
pages/course.html

我有嘗試在all.scss和main.js import jquery-ui，但有出錯所以先註解掉，直接用 cdn
我看原本npm就有下載 jQuery 但我上網看jquery-ui要用 jquery (q 是小寫)所以我有再下載  jquery ，但我不知道兩個差在哪XD

完成購務車頁面、更改文字內容

---

assets/js/account.js
assets/scss/pages/_account.scss
assets/scss/pages/_course_introduction.scss
pages/account.html
pages/course.html

1. 新增 從課程選單頁面點擊立即上課 可進入課程簡介
2. 調整 我的課表畫面、課程管理
3. 新增 課程管理 展示 修改時間並儲存 畫面會有所變化

更新部分課程管理功能

---

assets/scss/pages/_account.scss
assets/scss/pages/_course_introduction.scss
pages/account.html

新增個頁面的modal功能

---

assets/scss/pages/_course.scss
pages/cart.html
pages/cart2.html
pages/course.html

1. 篩選列表移到左邊
2. 篩選星等文字對應正確的 radio button
3. 新增購物車超商、ATM付款資訊
4. 修改購物車2預約附註(須至少預約一堂，剩餘堂數可在會員中心預約)、按鈕改成確定預約

fix: 課程列表篩選、購物車付款

---

assets/js/header.js
assets/scss/layout/_header.scss
layout/header.ejs

feat: 🎸 logout

---

assets/js/faq.js
main.js
pages/faq.html

目前只作出可以讓細項隱藏，還在研究怎麼讓沒有細項的類別隱藏大標題 (帳號設定、薪資相關...等藍底部分)

feat: 🎸 faq search

---

assets/scss/pages/_course.scss
pages/course.html

調整成要按篩選列的最面"篩選"按鈕才會篩選，但發現在選擇篩選時旁邊的課程篩選數量不會動好像怪怪的...考慮改成按一個就呼叫api篩選，像udemy一樣
目前有發現的BUG：選擇後端的C時會篩到C#，還在試要怎麼改，有用正規表達式/b /b，還是會篩到

Feat/filter 課程頁面的篩選功能

---

assets/js/coursePage/filter.js

更正BUG：因為不同的主題內有相同的項目(如前端和後端都有 javascript )導致的篩選異常

fix: 🐛 course filter function

---

assets/js/coursePage/api.js
assets/js/coursePage/search.js
assets/js/index.js

* 首頁 & 課程列表的搜尋功能 修改完畢
* 解決 首頁 12大分類按鈕篩選 時好時壞問題 😆😆

修改 搜尋功能和12大分類

---

assets/js/index.js

✅ 首頁 - 教師推薦：卡片出不來
✅ 首頁 - 熱門推薦教師：卡片高度不一致
✅ 首頁 - 學生好評：隨機取得 5星評論 4 個

fix: 🐛 index card-layout and reviews data

---

assets/js/firebase.js
assets/js/register.js
assets/scss/components/_btn.scss
pages/register.html

新增: 註冊頁面 發送手機驗證碼

---

assets/js/coursePage/search.js

修改：課程分類搜尋功能

---

assets/js/account.js
assets/js/appointment.js
assets/js/time_course.js
pages/account.html

選擇日期時，右邊可跟著動態找出當天可預約的日期。
ex: 點擊選取了'11/29' 就會找到此課程11/29當天可以預約哪些時間
課程預約部分:
也更新了老師如果有時間已被預約，會呈現disabled。

新增可過濾 已被預約走的課程

---

assets/js/faq.js
assets/scss/pages/_faq.scss
pages/faq.html

* 保留輸入的關鍵字 (原版本: 搜尋後清空 input)
* 新增 x 按鈕，清除關鍵字
* input 為空時，點擊 enter，會顯示所有內容

修改 常見問答搜尋功能

---

assets/js/coursePage/api.js
assets/js/coursePage/order.js

修改 首頁 - 熱門教師 查看更多按鈕

---

assets/js/coursePage/startCourse.js
assets/js/header.js
layout/loginModal.ejs
pages/login.html
pages/register.html

點擊購物車按鈕 或 立即上課按鈕
* 沒登入: 點擊後跳 modal，可以點擊連結跳轉登入頁面，不管有沒有點擊，5秒後自動跳轉。
* 畫面會顯示 數字倒數
* 點擊 modal closeBtn，停止跳轉
登入後
* 進行按鈕原本的動作 (跳轉購物車頁面，加入購物車)

修改 loginModal

---

assets/js/account_coupon.js
assets/js/cart2.js
assets/js/cartPage/coupon.js
assets/js/register.js
pages/register.html

註冊後登入按鈕下面新增一行字：首次登入即可獲得優惠券
註冊後新增 全課程9折優惠券、使用者裝預約資料的容器(cart2 預約完可看到 db json 的 user_courses 有新增預約時間)

feat: 🎸 new user add coupon and data

---

assets/scss/layout/_backtotop.scss
layout/backtotop.ejs

backToTop 按鈕

---

assets/js/login.js
assets/js/register.js
assets/scss/pages/_index.scss
pages/login.html
pages/register.html
vite.config.js

google 登入註冊整合一起
* 不管點擊 google 註冊或 google 登入，如果沒有帳號，會直接創立帳號並登入，如果有帳號就會登入成功
待改
* 錯誤訊息的排版還要調整

修改 google 登入註冊

---

assets/js/appointment.js
assets/js/cartPage/cart.js
assets/js/cartPage/coupon.js
assets/js/cartPage/payment.js
assets/js/coursePage/filter.js
assets/scss/components/_input-search.scss
pages/cart.html
pages/course.html

- 課程頁面：
1. 篩選的 checkbox 改成 hover 時有手指圖案
2. 修好 如果最小打 800，最大打 800，正常顯示，但如果刪掉其中一個，就變成 0 個結果了
- 購物車：
1. 信用卡驗證
2. 修好 本來已經選好 "下面" 那堂課的優惠券，但我去增加 "上面" 的堂數，"下面"的優惠券就不見了，反過來也是，點了下面 +，上面優惠券不見
3. 使用優惠券的 input 的 x 變大
- 會員中心：
1. 課程管理的圖片大小改成120px

fix: 🐛 bug

---

assets/js/coursePage/api.js
assets/js/coursePage/filter.js

fix: 🐛 filter rating number
